"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = __importStar(require("react"));
const styles_1 = require("@material-ui/core/styles");
const core_1 = require("@material-ui/core");
const useStyles = styles_1.makeStyles(theme => ({
    root: { width: '100%', },
    justify: { textAlign: 'justify' },
    highlighted: { backgroundColor: "#b3e5fc" },
    noDisplay: { display: 'none' },
    button: { marginTop: theme.spacing(1), marginRight: theme.spacing(1), },
    actionsContainer: { marginBottom: theme.spacing(2), },
    resetContainer: { padding: theme.spacing(3), },
    message: { marginTop: 20 },
    help: { color: '#0000FF', },
}));
const steps = ['Problem Statement', 'Receive Ballot', 'Vote', 'Turn Into 3 Ballots', 'Pick Verification Columns', 'Transmit & Get Receipts', 'Finish'];
function VerticalLinearStepper() {
    const classes = useStyles();
    const [voteStep, setvoteStep] = react_1.useState(0);
    const verbiage = [
        react_1.default.createElement("div", { className: classes.justify },
            react_1.default.createElement("p", null, "One of the barriers to blockchain voting is that most people don't know that it IS possible to make a vote both verifiable and anonymous --  while, also, preventing people from selling their votes."),
            react_1.default.createElement("p", null, "In 2006, an MIT professor, Ron Rivest, figured out that by giving each voter three ballots: one verifiable and two anonymous that any vote alteration or destruction has a 1 / 3 chance of being detected without revealing how the voter actually voted."),
            react_1.default.createElement("p", null, "With some simple software, it is possible to give a voter a single standard ballot, reap the advantages of the three ballot system and avoid its disadvantages (correlation attacks) -- all without making the voting process unduly onerous."),
            react_1.default.createElement("p", null, "This demo shows how this works. ")),
        react_1.default.createElement("div", { className: classes.justify },
            react_1.default.createElement("p", null, "First, the voter starts with a standard ballot."),
            react_1.default.createElement("p", null, "Behind the scenes, the blockchain passes the software three encryption keys and one decryption key for each office or ballot question."),
            react_1.default.createElement("p", null, "In our example, since there are two offices and one question, the blockchain will pass nine encryption keys and three decryption keys.")),
        react_1.default.createElement("div", { className: classes.justify },
            react_1.default.createElement("p", null, "The voter just votes normally."),
            react_1.default.createElement("p", null, "The software will, of course, prevent them from filling in too many boxes.")),
        react_1.default.createElement("div", { className: classes.justify },
            react_1.default.createElement("p", null, "Once the voter is done, the software randomly divides the ballot into three ballots (as shown)."),
            react_1.default.createElement("p", null, "Each option that the voter voted for is marked on two of the ballots. Each option that the voter did not vote for is marked on one ballot."),
            react_1.default.createElement("p", null, "After votes are counted and totalled, the number of voters is subtracted from each line to leave the correct vote count for each line.")),
        react_1.default.createElement("div", { className: classes.justify },
            react_1.default.createElement("p", null, "Then, the voter picks whch columns they wish to be able to verify.  In this case, it amused the voter to pick columns 3, 1 and 3 again."),
            react_1.default.createElement("p", null, "Any attempt to alter the vote before it hits the immutable blockchain has a one-third chance of being provably detected."),
            react_1.default.createElement("p", null, "Note, also, that any one column is *not* sufficient to prove how the voter voted.")),
        react_1.default.createElement("div", { className: classes.justify },
            react_1.default.createElement("p", null, "The software then sends all nine ballots (three for each office or question) to the blockchain."),
            react_1.default.createElement("p", null, "Once their vote is recorded, the voter is given a receipt for each question or office showing only their picked columns and a QR code encoding a URL that retrieves them from the blockchain and decrypts them."),
            react_1.default.createElement("p", null, "And, again, note that the receipts don't give any indication of how the voter actually voted -- thus not providing the proof necessary for a voter to sell their vote.")),
        react_1.default.createElement("div", { className: classes.justify },
            react_1.default.createElement("p", null, "After the voter goes home, they can always use their cell phone and the QR code to check the blockchain and verify that their selected columns are recorded correctly"),
            react_1.default.createElement("p", null, "If their vote was altered before transmission, it is a simple matter to prove that there is a problem when the receipt doesn't match the blockchain."))
    ];
    const handleNext = () => { setvoteStep(voteStep + 1); };
    const handleBack = () => { setvoteStep(voteStep - 1); };
    const handleReset = () => { setvoteStep(0); };
    return (react_1.default.createElement("table", null,
        react_1.default.createElement("tr", null,
            react_1.default.createElement("td", { style: { width: '20%' } },
                react_1.default.createElement("div", { className: classes.root },
                    react_1.default.createElement(core_1.Stepper, { activeStep: voteStep, orientation: "vertical" }, steps.map((label, index) => (react_1.default.createElement(core_1.Step, { key: label },
                        react_1.default.createElement(core_1.StepLabel, null, label),
                        react_1.default.createElement(core_1.StepContent, null,
                            react_1.default.createElement("table", null,
                                react_1.default.createElement("tr", null,
                                    react_1.default.createElement("td", null, voteStep === index ? react_1.default.createElement(core_1.Typography, { className: classes.message }) : null))),
                            react_1.default.createElement("div", { className: classes.actionsContainer },
                                react_1.default.createElement("div", null,
                                    react_1.default.createElement(core_1.Button, { disabled: voteStep === 0, onClick: handleBack, className: classes.button }, "Back"),
                                    react_1.default.createElement(core_1.Button, { disabled: false, variant: "contained", color: "primary", onClick: handleNext, className: classes.button }, voteStep === steps.length - 1 ? 'Finish' : 'Next')))))))),
                    voteStep === steps.length && (react_1.default.createElement(core_1.Paper, { square: true, elevation: 0, className: classes.resetContainer },
                        react_1.default.createElement(core_1.Typography, null, "All steps completed - you're finished"),
                        react_1.default.createElement(core_1.Button, { onClick: handleReset, className: classes.button }, "Reset"))))),
            react_1.default.createElement("td", null, "  \u00A0  \u00A0  \u00A0 "),
            react_1.default.createElement("td", null,
                react_1.default.createElement("table", { className: voteStep > 0 && voteStep < 6 ? '' : classes.noDisplay },
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", { colSpan: 5 }, "Local Delegate - choose one")),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", { colSpan: 5 },
                            react_1.default.createElement("hr", null))),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null, "Awesome Leader"),
                        react_1.default.createElement("td", { rowSpan: 3 }, " \u00A0 "),
                        react_1.default.createElement("td", { rowSpan: 3 },
                            react_1.default.createElement("img", { className: voteStep == 5 ? '' : classes.noDisplay, src: "..\\src\\images\\QR1.png", width: "70 px" })),
                        react_1.default.createElement("td", { rowSpan: 3 }, " \u00A0 "),
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("input", { type: "checkbox", checked: voteStep > 1 && voteStep < 5 ? true : false })),
                        react_1.default.createElement("td", null, " \u00A0 \u00A0  \u00A0 \u00A0  \u00A0 \u00A0 "),
                        react_1.default.createElement("td", null, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null, " \u00A0 \u00A0 \u00A0 "),
                        react_1.default.createElement("td", null, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null, " \u00A0 \u00A0 \u00A0 "),
                        react_1.default.createElement("td", { className: voteStep > 3 ? classes.highlighted : '' }),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null, " \u00A0 \u00A0  \u00A0 \u00A0  \u00A0 \u00A0 ")),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null, "Dismal Failure"),
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("input", { type: "checkbox" })),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null, " \u00A0 "),
                        react_1.default.createElement("td", null, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", { className: voteStep > 3 ? classes.highlighted : '' }),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null)),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null, "Sociopath"),
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("input", { type: "checkbox", checked: voteStep > 4 ? true : false })),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null, " \u00A0 "),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", { className: voteStep > 3 ? classes.highlighted : '' }, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null)),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("br", null))),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", { colSpan: 5 }, "At-Large Delegates - choose two")),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", { colSpan: 5 },
                            react_1.default.createElement("hr", null))),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null, "Exceptional Woman"),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("input", { type: "checkbox", checked: voteStep > 1 ? true : false })),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", { className: voteStep > 3 ? classes.highlighted : '' }, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null, " \u00A0 "),
                        react_1.default.createElement("td", null, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null)),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null, "Great Man"),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("input", { type: "checkbox", checked: voteStep > 1 && voteStep < 5 ? true : false })),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", { className: voteStep > 3 ? classes.highlighted : '' }),
                        react_1.default.createElement("td", null, " \u00A0 "),
                        react_1.default.createElement("td", null, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null)),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null, "Con Man"),
                        react_1.default.createElement("td", { rowSpan: 3 }, " \u00A0 "),
                        react_1.default.createElement("td", { rowSpan: 3 },
                            react_1.default.createElement("img", { className: voteStep == 5 ? '' : classes.noDisplay, src: "..\\src\\images\\QR2.png", width: "60 px" })),
                        react_1.default.createElement("td", { rowSpan: 3 }, " \u00A0 "),
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("input", { type: "checkbox", checked: voteStep > 4 ? true : false })),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", { className: voteStep > 3 ? classes.highlighted : '' }, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null, " \u00A0 "),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null)),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null, "Deliquent"),
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("input", { type: "checkbox" })),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", { className: voteStep > 3 ? classes.highlighted : '' }),
                        react_1.default.createElement("td", null, " \u00A0 "),
                        react_1.default.createElement("td", null, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null)),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null, "Mob Boss"),
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("input", { type: "checkbox" })),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", { className: voteStep > 3 ? classes.highlighted : '' }),
                        react_1.default.createElement("td", null, " \u00A0 "),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null)),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null, "Moron"),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("input", { type: "checkbox", checked: voteStep > 4 ? true : false })),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", { className: voteStep > 3 ? classes.highlighted : '' }, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null, " \u00A0 "),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null)),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null, "Recently Deceased"),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("input", { type: "checkbox" })),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", { className: voteStep > 3 ? classes.highlighted : '' }),
                        react_1.default.createElement("td", null, " \u00A0 "),
                        react_1.default.createElement("td", null, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null)),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("br", null))),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", { colSpan: 5 }, "Ballot Question")),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", { colSpan: 5 },
                            react_1.default.createElement("hr", null))),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null, "Right Answer"),
                        react_1.default.createElement("td", { rowSpan: 3 }, " \u00A0 "),
                        react_1.default.createElement("td", { rowSpan: 3 },
                            react_1.default.createElement("img", { className: voteStep == 5 ? '' : classes.noDisplay, src: "..\\src\\images\\QR3.png", width: "60 px" })),
                        react_1.default.createElement("td", { rowSpan: 3 }, " \u00A0 "),
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("input", { type: "checkbox", checked: voteStep > 1 && voteStep < 5 ? true : false })),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null, " \u00A0 "),
                        react_1.default.createElement("td", null, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", { className: voteStep > 3 ? classes.highlighted : '' }),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null)),
                    react_1.default.createElement("tr", null,
                        react_1.default.createElement("td", null, "Wrong Answer"),
                        react_1.default.createElement("td", null,
                            react_1.default.createElement("input", { type: "checkbox", checked: voteStep > 4 ? true : false })),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null, " \u00A0 "),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", { className: voteStep > 3 ? classes.highlighted : '' }, voteStep > 2 ? 'X' : ''),
                        react_1.default.createElement("td", null),
                        react_1.default.createElement("td", null)),
                    react_1.default.createElement("tr", null))),
            react_1.default.createElement("td", { style: { width: '30%' } }, verbiage[voteStep]),
            react_1.default.createElement("td", { style: { width: '20%' } }))));
}
exports.default = VerticalLinearStepper;
//# sourceMappingURL=VotingDemo.js.map